name: Shitaraba Health Check

on:
  push:
  schedule:
  - cron: '*/10 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
    - name: URL Health Check
      uses: Jtalk/url-health-check-action@v1.3
      with:
        url: https://jbbs.shitaraba.net/internet/24795/head.txt
        max-attempts: 2
        retry-delay: 5s
    - name: Ping2HelthCheckIO
      if: ${{ success() }}
      uses: Jtalk/url-health-check-action@v1.3
      with:
        url: ${{secrets.HEALTHCHECKS_IO_PING_URL}}
        max-attempts: 1
        retry-delay: 5s
